Proyecto_Final_Progra_Web/FrontEnd/Controllers/CartaController.cs
using FrontEnd.Helpers.Intefaces;
using FrontEnd.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace FrontEnd.Controllers
{
    public class CartaController : Controller
    {
        ICartaHelper CartaHelper;

        public CartaController(ICartaHelper cartaHelper)
        {
            CartaHelper = cartaHelper;
        }
        // GET: CartaController
        public async Task<ActionResult> Index()
        {
            return View(await CartaHelper.GetCartas());
        }

        // GET: CartaController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            CartaViewModel carta = await CartaHelper.GetCarta(id);
            return View(carta);
        }

        // GET: CartaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: CartaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CartaViewModel carta)
        {
            try
            {
                await CartaHelper.Add(carta);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CartaController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            CartaViewModel carta = await CartaHelper.GetCarta(id);
            return View(carta);
        }

        // POST: CartaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(CartaViewModel carta)
        {
            try
            {
                await CartaHelper.Update(carta);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CartaController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            CartaViewModel carta = await CartaHelper.GetCarta(id);
            return View(carta);
        }

        // POST: CartaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(CartaViewModel carta)
        {
            try
            {
                await CartaHelper.Remove(carta.CartaId);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Proyecto_Final_Progra_Web/FrontEnd/Controllers/MazoController.cs
using Entities.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FrontEnd.Models;
using System.Linq;
using System.Threading.Tasks;
using FrontEnd.Helpers.Implementations;
using FrontEnd.Helpers.Intefaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.Build.Framework;
using System.Security.Claims;

namespace FrontEnd.Controllers
{
    public class MazoController : Controller
    {
        IMazoHelper _MazoHelper;


        private readonly ProyectoFinalWebContext _context;
        private readonly UserManager<ApplicationUser> _userManager;

        public MazoController(IMazoHelper mazoHelper, ProyectoFinalWebContext context , UserManager<ApplicationUser> userManager)
        {
           _MazoHelper = mazoHelper;
            _userManager = userManager;
            _context = context;
        }


        [Authorize]
        // GET: Mazos
        public async Task<IActionResult> Index()


        {
            var isCliente = User.IsInRole("Usuario");

            List<Mazo> mazos;
            if (isCliente)
            {
                // Obtener el ID del cliente actual
                var clienteId = User.FindFirstValue(ClaimTypes.NameIdentifier);


                mazos = await _context.Mazos
                    .Where(c => c.UsuarioId == clienteId)
                    .Include(c => c.NombreMazo)
                    .Include(c => c.CreadoEn)
                    .Include(c => c.UsuarioModificacion)
                    .ToListAsync();
            }
            else
            {

                mazos = await _context.Mazos
                    .Include(c => c.NombreMazo)
                    .Include(c => c.CreadoEn)
                    .Include(c => c.UsuarioModificacion)
                    .ToListAsync();
            }

            return View(mazos);
        }


        [Authorize]
        public async Task<IActionResult> MisMazos()
        {
            // Obtener el ID del usuario actual
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);


            var mazos = await _context.Mazos
                .Where(c => c.UsuarioId == userId)
                .ToListAsync();

            return View(mazos);
        }

        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            var ci = _context.Mazos.FirstOrDefault(c => c.MazoId == id);

            if (ci == null)
            {
                return NotFound();
            }

           var mazos = await _context.Mazos
            .Include(c => c.NombreMazo)
            .Include(c => c.CreadoEn)
            .Include(c => c.UsuarioModificacion)
            .ToListAsync();

            if (mazos == null)
            {
                return NotFound();
            }


            return View(mazos);
        }

        // GET: Citas/Create
        [Authorize]
        public IActionResult Create()
        {
            ViewData["MazoId"] = new SelectList(_context.Mazos, "MazoId", "Nombre");
            ViewData["UsuarioModificacionId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Nombre");


            //ViewData["Veterinario"] = new SelectList(veterinarios, "Value", "Text");

            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Mazo mazo)
        {
            if (mazo.MazoId == 0)
            {
                // Agregar un error de modelo para mostrar un mensaje al usuario
                ModelState.AddModelError("", "No hay mazos registrados, se debe crear al menos un mazo para crear el mazo");
            }

            if (ModelState.IsValid)
            {
                DateTime fechaCita = mazo.CreadoEn.Date;

                var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
                mazo.UsuarioId = userId;

                var isCliente = User.IsInRole("Cliente");

                // Verificar si la cita es creada por un veterinario
                if (isCliente)
                {
                    // Guardar la cita en la base de datos
                    _context.Add(mazo);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    mazo.Estado = "Creado";
                }


            }
            ViewData["MazoId"] = new SelectList(_context.Mazos, "MazoId", "Nombre", mazo.MazoId);
            ViewData["UsuarioId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", mazo.UsuarioId);
            ViewData["UsuarioModificacion"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", mazo.UsuarioModificacion);


            return View(mazo);


        }


        // GET: Citas/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }

            var mazo = await _context.Mazos.FindAsync(id);
            if (mazo == null)
            {
                return NotFound();
            }
            ViewData["MazoId"] = new SelectList(_context.Mazos, "MazoId", "Nombre", mazo.MazoId);
            ViewData["UsuarioId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", mazo.UsuarioId);
            ViewData["UsuarioModificacionId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", mazo.UsuarioModificacion);



            return View(mazo);
        }


        // POST: Citas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("MazoId,UsuarioId,UsuarioModificacionId,NombreMazo,CreadoEn,Estado")] Mazo mazo)
        {
            if (id != mazo.MazoId)
            {
                return NotFound();
            }


            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mazo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!mazoExist(mazo.MazoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["MazoId"] = new SelectList(_context.Mazos, "MazoId", "Nombre", mazo.MazoId);
            ViewData["UsuarioId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", mazo.UsuarioId);
            ViewData["UsuarioModificacionId"] = new SelectList(_context.Set<ApplicationUser>(), "Id", "Id", mazo.UsuarioModificacion);


            return View(mazo);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mazos = await _context.Mazos
                    .Include(c => c.NombreMazo)
                    .Include(c => c.CreadoEn)
                    .Include(c => c.UsuarioModificacion)
                .FirstOrDefaultAsync(m => m.MazoId == id);
            if (mazos == null)
            {
                return NotFound();
            }

            var citas = _context.Mazos.FirstOrDefault(c => c.MazoId == id);


            return View(mazos);
        }

        // POST: Citas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mazos = await _context.Mazos.FindAsync(id);
            if (mazos != null)
            {
                _context.Mazos.Remove(mazos);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool mazoExist(int id)
        {
            return _context.Mazos.Any(e => e.MazoId == id);
        }

    }
}

Proyecto_Final_Progra_Web/FrontEnd/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FrontEnd</title>
    <link rel="icon" href="https://us.123rf.com/450wm/maralingstad/maralingstad1506/maralingstad150600193/40817856-vector-juego-de-tarjetas-de-icono-eps10.jpg?ver=6">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FrontEnd.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-body-tertiary" style="background-color: #4CAF50;">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index" style="color:black">Inicio</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (User.IsInRole("Cliente"))
                        {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color:black" asp-area="/Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color:black" asp-area="/Ayuda">Ayuda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" style="color:black" asp-area="/Soporte">Soporte</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Carta" asp-action="Index">Cartas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Mazo" asp-action="Index">Mazos</a>
                        </li>
                        }
                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index"> Usuarios </a>
                            </li>
                        }
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer mt-auto py-3">
        <div class="container text-center">
            <span class="text-muted">© @DateTime.Now.Year Mi Juego de Cartas. Todos los derechos reservados.</span>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>